version: '3'

services:
###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    depends_on:
      - myapp
###< symfony/mailer ###
