version: '3'

services:
  myapp:
    image: docker.io/bitnami/symfony:1
    ports:
      - '8000:8000'
    volumes:
      - '.:/app/ToDoAPI'
    environment:
      - SYMFONY_PROJECT_NAME=ToDoAPI
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=alvaro
      - MARIADB_PASSWORD=alvaro
      - MARIADB_DATABASE=ToDo_BD
    container_name: symfony_container
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: docker.io/mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ToDo_BD
      - MYSQL_PORT_NUMBER=3306
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=alvaro
      - MYSQL_USER=alvaro
      - MYSQL_PASSWORD=alvaro
    volumes:
      - db:/var/lib/mysql/
      - ./ToDo.sql:/docker-entrypoint-initdb.d/ToDo.sql
volumes:
  db: